loaded_h_0(function(_){var window=this;
_.wYq=_.y("I9y8sd",[]);
_.v("I9y8sd");
var xYq=function(){return google.ht&&google.ht<Date.now()&&!google.fuht?!0:!1},yYq=function(){return google.lfm&&google.lfm.some(a=>a.ie())},zYq=function(a){a=getComputedStyle(a);if(a.display==="none")return"display: none";if(Number(a.opacity)<.5)return`opacity: ${a.opacity}`;if(a.visibility==="hidden")return"visibility: hidden"},AYq=function(a,b,c,d,{logError:e}){d=_.gf(d);b=`${b}-${c}-${_.xna(d)}`;const f=a.get(b),g=_.hf(d,"am");if(g){if(f){if(g===f)return;let h=`k=${_.xna(d)}`;(d=_.hf(d,"ck"))&&
(h=`${h}.ck=${d}`);e(Error("dw`"+JSON.stringify({type:c,C3f:h,P0f:f,u0f:g})))}a.set(b,g)}},CYq=function(a){if(a.toggle){var b;a.sampleRate=(b=a.sampleRate)!=null?b:.01;BYq.push(a)}},DYq={name:"umods"},EYq=!!(_.Mi[19]>>27&1),FYq=!!(_.Mi[19]>>28&1),GYq=!!(_.Mi[19]>>29&1),HYq=!!(_.Mi[20]&1),IYq=!!(_.Mi[20]&2),JYq=!!(_.Mi[20]&4),KYq=!!(_.Mi[20]&8);var LYq=["google.com","youtube.com","ampproject.org","adtrafficquality.google",(new URL(location.href)).host];var BYq=[],MYq=[],NYq=class extends _.ls{static Sa(){return{}}constructor(){super();this.Ca=Math.random();this.Aa=!1;this.logError=this.logError.bind(this);window.addEventListener("pagehide",()=>{this.Aa=!0});window.addEventListener("pageshow",()=>{this.Aa=!1});google.sx(null,()=>{(0,_.Zn)(()=>{this.Ba()},2E3)})}Ba(){if(!this.Aa)for(const a of BYq)this.sample(a,()=>{a.run({logError:(b,c={})=>{this.logError(a.name,b,c)}})})}logError(a,b,c={}){if(!this.oa){this.oa={};for(const d of MYq)this.sample(d,
()=>{const e=d.run();e&&(this.oa=Object.assign({},this.oa,e))})}_.kf(b,{level:0,Bf:Object.assign({},{src:"bad_srp_detection"},c,this.oa)});FYq&&navigator.sendBeacon(`/gen_204?atyp=i&bsf=${a}.1&ei=${(0,_.km.qy)()}`,"")}sample(a,b){((a.H3f?Math.random():this.Ca)<(a.sampleRate||0)||EYq)&&b()}};NYq.prototype.$wa$rT3LBf=function(){return this.Ba};
CYq({name:"fi",run:function({logError:a}){const b={},c=Array.from(document.querySelectorAll("iframe")).map(d=>{try{return d.src&&d.src.length!==0?(new URL(d.src)).hostname:void 0}catch(e){return e.toString()}}).filter(d=>{if(!d)return!1;d=d.split(".");for(const e of LYq)if(d.slice(-1*e.split(".").length).join(".").toLowerCase()===e)return!1;return!0});if(c.length){b.count=String(c.length);for(let d=0;d<Math.min(c.length,3);d++)b[`iframe_${d+1}`]=c[d];a(Error("ew"),b)}},toggle:HYq});
CYq({name:"hp",run:function({logError:a}){if(!xYq()){for(var b=document.elementFromPoint(window.innerWidth/2,window.innerHeight/2),c=[];b;)c.unshift(b),b=b.parentElement;for(const d of c){if(d.offsetWidth<window.innerWidth*.6||d.offsetHeight<200)break;const e=zYq(d);if(e){const f=d;(0,_.Zn)(()=>{e===zYq(f)&&a(Error("fw"),{hiddenProperty:e,id:f.id,tagName:f.tagName,classes:f.classList.value,styles:f.getAttribute("style")||""})},1E3);break}}}},toggle:GYq});
CYq({name:"sp",run:function({logError:a}){var b;if(b=!xYq())b=document.body.querySelector("[jsname=KG3hVc]"),b=!(b&&window.getComputedStyle(b).display!=="none")&&!yYq();if(b){b=document.body.clientHeight;var c,d=((c=document.getElementById("rcnt")||document.getElementById("center_col"))==null?void 0:c.clientHeight)||0;(b<400||d<100)&&a(Error("gw"),{pageHeight:String(b),resultsHeight:String(d)})}},toggle:GYq});
CYq({name:"qm",run:function({logError:a}){document.compatMode==="BackCompat"&&a(Error("hw"))},toggle:IYq});
CYq({name:"um",run:function({logError:a}){var b=google.erd;if(b){var c=b.bv;if(c&&(b=b.dpf)){var d,e=(d=navigator)==null?void 0:d.userAgent;if(e){d=_.wg("s",DYq);c=`${c}-${b}-${e}`;var f;(b=(f=google.xjs)==null?void 0:f.basejs)&&AYq(d,c,"jsurl",b,{logError:a});var g;(f=(g=google.xjs)==null?void 0:g.basecss)&&AYq(d,c,"cssurl",f,{logError:a});var h;(g=(h=google.xjs)==null?void 0:h.basecomb)&&AYq(d,c,"comburl",g,{logError:a})}}}},toggle:KYq});
var OYq={name:"nn",run:function(){var a=document.querySelectorAll("script:not([nonce])");if(a.length!==0){var b={nonce_count:String(a.length)},c=0;for(const d of a){a=d.src;let e;if((e=a)==null?0:e.startsWith("https://www.gstatic.com/"))return;if(c++>3)break;let f;const g=(f=d.textContent)==null?void 0:f.substring(0,300);g&&(b[`nonce_script_${c}`]=g);a&&(b[`nonce_src_${c}`]=a)}return b}},toggle:JYq};if(OYq.toggle){var PYq;OYq.sampleRate=(PYq=OYq.sampleRate)!=null?PYq:1;MYq.push(OYq)}_.ps(_.wYq,NYq);
_.x();
_.Af(_.W6a);
_.v("NEW1Qc");
var ujo=class extends _.ho{isAvailable(){return!1}oa(){_.Hi("Translation","openUrlWithTranslation")}};_.$f(_.V6a,ujo);
_.x();
_.v("xBbsrc");
_.wjo=new _.Sf(_.W6a);
_.x();
_.Cjo=_.y("DLOxie",[_.W6a,_.Nq]);
var Apc,Bpc,Cpc,Dpc,Fpc,Gpc,Ipc,Hpc,Kpc,Lpc,Mpc,Jpc;Apc=function(...a){return new _.jQa(a.map(_.Lqa))};Bpc=_.ea.URL;_.Epc=(_.ea==null?void 0:(Cpc=_.ea.document)==null?void 0:Cpc.baseURI)||((Dpc=_.ea.location)==null?void 0:Dpc.href)||"";try{new Bpc("http://example.com"),Fpc=!0}catch(a){Fpc=!1}Gpc=Fpc;
Ipc=class{constructor(a){this.oa=new Map;a.indexOf("?")==0&&(a=a.substring(1));a=a.split("&");for(let c of a){a=c;let d="";var b=c.split("=");b.length>1&&(a=decodeURIComponent(b[0].replace("+"," ")),d=decodeURIComponent(b[1].replace("+"," ")));b=this.oa.get(a);b==null&&(b=[],this.oa.set(a,b));b.push(d)}}get(a){return(a=this.oa.get(a))&&a.length?a[0]:null}getAll(a){return[...(this.oa.get(a)||[])]}has(a){return this.oa.has(a)}[Symbol.iterator](){return Apc(..._.iQa(this.oa,a=>{const b=a[0];return _.iQa(a[1],
c=>[b,c])}))}toString(){return Hpc(this)}};Hpc=function(a){const b=c=>encodeURIComponent(c).replace(/[!()~']|(%20)/g,d=>({"!":"%21","(":"%28",")":"%29","%20":"+","'":"%27","~":"%7E"})[d]);return Array.from(a,c=>b(c[0])+"="+b(c[1])).join("&")};
Kpc=function(a){const b=_.Cm("A");let c;try{_.Fc(b,_.cc(a)),c=b.protocol}catch(e){throw Error("ih`"+a);}if(c===""||c===":"||c[c.length-1]!=":")throw Error("ih`"+a);if(!Jpc.has(c))throw Error("ih`"+a);if(!b.hostname)throw Error("ih`"+a);const d=b.href;a={href:d,protocol:b.protocol,username:"",password:"",hostname:b.hostname,pathname:"/"+b.pathname,search:b.search,hash:b.hash,toString:()=>d};Jpc.get(b.protocol)===b.port?(a.host=a.hostname,a.port="",a.origin=a.protocol+"//"+a.hostname):(a.host=b.host,
a.port=b.port,a.origin=a.protocol+"//"+a.hostname+":"+a.port);return a};Lpc=function(a,b){return a&&b?a+":"+b+"@":a?a+"@":b?":"+b+"@":""};
Mpc=function(a){let b;try{b=new Bpc(a)}catch(d){throw Error("ih`"+a);}const c=Jpc.get(b.protocol);if(!c)throw Error("ih`"+a);if(!b.hostname)throw Error("ih`"+a);if(b.origin!="null")return b;a={href:b.href,protocol:b.protocol,username:"",password:"",host:b.host,port:b.port,hostname:b.hostname,pathname:b.pathname,search:b.search,hash:b.hash};a.origin=c===b.port?b.protocol+"//"+b.hostname:b.protocol+"//"+b.hostname+":"+b.port;return a};
_.Ty=function(a,b){if(Gpc){if(!b)return Mpc(a);b=Mpc(b);try{return Mpc(a)}catch(e){}return new Bpc(a,b.href)}if(!b)return Kpc(a);b=Kpc(b);try{return Kpc(a)}catch(e){}const c=b.protocol+"//"+Lpc(b.username,b.password)+b.host;var d=a[0];d==="/"||d==="\\"?a=c+a:d==="?"?a=c+b.pathname+a:d&&d!=="#"?(d=b.pathname.lastIndexOf("/"),a=c+(d>0?b.pathname.substring(0,d):"")+"/"+a):a=c+b.pathname+b.search+a;return Kpc(a)};Jpc=new Map([["http:","80"],["https:","443"],["ws:","80"],["wss:","443"],["ftp:","21"]]);
_.Uy=function(a){return Gpc&&a.searchParams?a.searchParams:new Ipc(a.search)};
_.Npc=function(a,b){let c={};b&&(c.protocol=b.protocol,c.username=b.username,c.password=b.password,c.hostname=b.hostname,c.port=b.port,c.pathname=b.pathname,c.search=b.search,c.hash=b.hash);Object.assign(c,a);if(c.port&&c.port[0]===":")throw Error("jh");c.hash&&c.hash[0]!="#"&&(c.hash="#"+c.hash);a.search?a.search[0]!="?"&&(c.search="?"+a.search):a.searchParams&&(c.search="?"+Hpc(a.searchParams),c.searchParams=void 0);a="";c.protocol&&(a+=c.protocol+"//");a+=Lpc(c.username,c.password);a+=c.hostname||
"";c.port&&(a+=":"+c.port);a+=c.pathname||"";a+=c.search||"";a+=c.hash||"";return _.Ty(a)};
_.v("DLOxie");
var Djo=function(a){try{const b=_.Ty(a);return b.hostname!=null&&b.hostname.endsWith(".search.translate.goog")}catch(b){return!1}},Ejo=RegExp("^(.+)[.]([a-zA-Z]+)2([a-zA-Z]+)[.]search[.]translate[.]goog");var Fjo={childList:!0,subtree:!0,attributes:!0,attributeFilter:["href"]},Jjo=function(a,b){if(Djo(b.href))try{var c=b.href;if(!Djo(c))throw Error("pr`"+c);const e=_.Ty(c),f=e.hostname.match(Ejo);if(!f||f.length!==4)throw Error("qr`"+c);const g=f[1],h=f[2],k=f[3];if(h.length!==2||!/^[a-zA-Z]+$/.test(h))throw Error("rr`"+c);if(k.length!==2||!/^[a-zA-Z]+$/.test(k))throw Error("sr`"+c);var d={Xea:_.Npc({hostname:g},e).href,c2:h,B_:k};_.bh().Ic("toledo_url",b.href).log();_.Fc(b,d.Xea)}catch(e){}(a.Aa||
a.Ca)&&(d=Gjo(a,b))&&(Hjo(a,b,d)||Ijo(b,d))},Gjo=function(a,b){if(!b.href)return null;let c,d;try{b=c=_.Ty(b.href);let f=!1;if((b.hostname==="google.com"||b.hostname==="www.google.com"||b.hostname===a.xc.location.hostname)&&b.pathname==="/url"){f=!0;var e=_.Uy(b);e.has("q")?b=_.Ty(e.get("q")):e.has("url")&&(b=_.Ty(e.get("url")))}({url:c,Hzb:d}={url:b,Hzb:f})}catch(f){return null}if(c.hostname!=="translate.google.com"||c.pathname!=="/translate")return null;a=_.Uy(c);if(!a.has("u")||!a.has("tl")||!a.has("sl"))return null;
e=a.get("u");e+=c.hash!=="#"?c.hash:"";return{Hzb:d,z1b:c.href,mab:e,E0b:a.get("tl"),g_a:a.get("sl")}},Hjo=function(a,b,c){if(!a.oa.isAvailable())return!1;_.Fc(b,c.mab);b.addEventListener("click",d=>{d.preventDefault();_.Vv(b,{userAction:3,data:{url:c.z1b}});a.oa.oa(c.mab,c.E0b,c.g_a,_.qd())});return!0},Ijo=function(a,b){HTMLAnchorElement.prototype.hasOwnProperty("hrefTranslate")&&(_.Fc(a,b.mab),a.setAttribute("hrefTranslate",b.E0b),b.Hzb&&a.addEventListener("click",async()=>{var c=(0,_.Pf)(),d=c();
c=c(1);try{c(await d(_.Vv(a,{userAction:3,data:{url:b.z1b}})))}finally{d()}}))},Kjo=class extends _.ls{static Sa(){return{service:{zk:_.wjo,xc:_.Wx}}}constructor(a){super();this.hj=null;this.Ba=b=>{for(const c of b)c.type==="childList"?c.addedNodes.forEach(d=>{d.nodeType===Node.ELEMENT_NODE&&(d.matches("a")&&Jjo(this,d),d instanceof Element&&d.querySelectorAll("a").forEach(e=>{Jjo(this,e)}))}):c.type==="attributes"&&c.attributeName==="href"&&c.target.matches("a")&&Jjo(this,c.target)};this.oa=a.service.zk;
this.xc=a.service.xc;this.hj=new MutationObserver(this.Ba);this.Aa=this.getData("cte").Nb();this.Ca=this.getData("ste").Nb()}Rd(){document.documentElement.querySelectorAll("a").forEach(a=>{Jjo(this,a)});this.hj.observe(document.body,Fjo)}Xc(){super.Xc();this.hj&&this.hj.disconnect()}};Kjo.prototype.$wa$mU5qzf=function(){return this.Xc};Kjo.prototype.$wa$npT2md=function(){return this.Rd};_.ps(_.Cjo,Kjo);
_.x();
});
// Google Inc.
